name: Spaces LLVM Build Workflow

on: workflow_dispatch

permissions:
  contents: write 

jobs:
  run-spaces:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      GH_TOKEN: ${{ github.token }}
      GIT_TERMINAL_PROMPT: 0

    steps:
      - name: Install Spaces CLI
        uses: work-spaces/install-spaces@v0.10.3

      - name: Clone Workflows Repository
        run: git clone https://github.com/work-spaces/workflows.git
      
      - name: Spaces Version
        run: spaces --version

      - name: Spaces Checkout
        run: spaces checkout --workflows/preload --workflows/llvm16-config --script=workflows/llvm-build --name=workspace

      - name: Spaces Run
        run: cd workspace && spaces run
