name: Spaces LLVM Build Workflow

on: workflow_dispatch

jobs:
  run-spaces:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      # Step 1: Install the Spaces CLI tool
      - name: Install Spaces CLI
        uses: work-spaces/install-spaces@v0.10.1

      # Step 2: Clone Workflows Repository
      - name: Clone Workflows Repository
        run: |
          git clone https://github.com/work-spaces/workflows.git

      # Step 3: Spaces Checkout
      - name: Spaces Checkout
        run: |
          spaces checkout --spaces-starlark-sdk --script=workflows/ninja-build --name=ninja-build
        env:
           GH_TOKEN: ${{ github.token }}

      # Step 4: Spaces Run
      - name: Spaces Run
        run: |
          cd ninja-build
          spaces run
        env:
           GH_TOKEN: ${{ github.token }}
