name: Spaces Ninja Build Workflow

on: workflow_dispatch

permissions:
  contents: write 

jobs:
  run-spaces:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14-large]
    env:
      GH_TOKEN: ${{ github.token }}
      GIT_TERMINAL_PROMPT: 0

    steps:
      - name: Install Spaces CLI
        uses: work-spaces/install-spaces@v0.10.2

      - name: Clone Workflows Repository
        run: git clone https://github.com/work-spaces/workflows.git
      
      - name: Spaces Version
        run: spaces --version

      - name: Spaces Checkout
        run: spaces --verbosity=trace checkout --spaces-starlark-sdk --script=workflows/ninja-build --name=ninja-build

      - name: Spaces Run
        run: cd ninja-build && spaces --verbosity=trace run
